
// This file has been generated by the GUI designer. Do not modify.
namespace Trilogic
{
	public partial class CompareWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Trilogic.CompareWindow
			this.Name = "Trilogic.CompareWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Compare Schema");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Container child Trilogic.CompareWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w1.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
